### ISSUE TITLE
Criar música do encontro com o antagonista

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/TestGame#10]
```yaml
start_date: 2021/8/31
due_date: 2021/8/31
progress: 0.1
parent: 0
```
