### ISSUE TITLE
Providenciar som de trovão

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/TestGame#11]
```yaml
start_date: 2021/8/31
due_date: 2021/8/31
progress: 0.1
parent: 0
```
