### ISSUE TITLE
Providenciar som de passos na areia

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/TestGame#13]
```yaml
start_date: 2021/8/31
due_date: 2021/8/31
progress: 0.1
parent: 0
```
