### ISSUE TITLE
Providenciar som de passos na pedra

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/TestGame#15]
```yaml
start_date: 2021/8/31
due_date: 2021/8/31
progress: 0.1
parent: 0
```
