### ISSUE TITLE
Criar/Providenciar elementos da UI

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/TestGame#16]
```yaml
start_date: 2021/8/31
due_date: 2021/8/31
progress: 0.1
parent: 0
```
