### ISSUE TITLE
Providenciar vegetação para a ilha

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/TestGame#20]
```yaml
start_date: 2021/8/31
due_date: 2021/8/31
progress: 0.1
parent: 0
```
