### ISSUE TITLE
Definir diálogo final

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/TestGame#27]
```yaml
start_date: 2021/8/31
due_date: 2021/8/31
progress: 0.1
parent: 0
```
