### ISSUE TITLE
Definir mecânica da batalha final

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/TestGame#28]
```yaml
start_date: 2021/8/31
due_date: 2021/8/31
progress: 0.1
parent: 0
```
