### ISSUE TITLE
Criar sala do encontro com o antagonista

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/TestGame#34]
```yaml
start_date: 2021/09/03
due_date: 2021/09/03
progress: 0.0
parent: 0
```
