### ISSUE TITLE
Definir o modelo do antagonista

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/TestGame#5]
```yaml
start_date: 2021/8/29
due_date: 2021/8/29
progress: 0.1
parent: 0
```
