### ISSUE TITLE
Criar música do menu principal

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/TestGame#6]
```yaml
start_date: 2021/8/29
due_date: 2021/8/29
progress: 0.0
parent: 0
```
