### ISSUE TITLE
Criar música da ilha

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/TestGame#7]
```yaml
start_date: 2021/8/29
due_date: 2021/8/29
progress: 0.1
parent: 0
```
