### ISSUE TITLE
Criar música dos enigmas do castelo

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/TestGame#8]
```yaml
start_date: 2021/8/29
due_date: 2021/8/29
progress: 0.1
parent: 0
```
